// <auto-generated />
using System;
using Impresent.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace impresent.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210222202607_volunteering")]
    partial class volunteering
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Impresent.Web.Model.Dtos.Volunteering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PresenceDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PresenceDayId");

                    b.HasIndex("StudentId");

                    b.ToTable("Volunteerings");
                });

            modelBuilder.Entity("Impresent.Web.Model.PresenceDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("PresenceDay");
                });

            modelBuilder.Entity("Impresent.Web.Model.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Impresent.Web.Model.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastPresence")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Impresent.Web.Model.Dtos.Volunteering", b =>
                {
                    b.HasOne("Impresent.Web.Model.PresenceDay", "PresenceDay")
                        .WithMany()
                        .HasForeignKey("PresenceDayId");

                    b.HasOne("Impresent.Web.Model.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("PresenceDay");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Impresent.Web.Model.PresenceDay", b =>
                {
                    b.HasOne("Impresent.Web.Model.Promotion", null)
                        .WithMany("PresenceDays")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Impresent.Web.Model.Student", b =>
                {
                    b.HasOne("Impresent.Web.Model.Promotion", null)
                        .WithMany("Students")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Impresent.Web.Model.Promotion", b =>
                {
                    b.Navigation("PresenceDays");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
