name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build the Docker image
      run: cd ImPresent.Web && docker build -t ombrelin/impresent:1.0 . --file Dockerfile
    - name: Docker login
      run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login --username ombrelin --password-stdin
    - name: Publish to Docker hub
      run: docker push ombrelin/impresent:1.0
